- name: Configure NetPlan configuration file
  ansible.builtin.copy:
    content: |
      # This is the network config written by 'subiquity'
      network:
        ethernets:
          {{ interface_name }}:
            addresses:
            - {{ static_ip }}
            gateway4: {{ gateway4_ip }}
            nameservers:
              addresses:
              - {{ address_ip }}
              search: []
        version: 2
    dest: '{{ network_config_path }}'
  when: ansible_facts['os_family'] == "Ubuntu"